name: CI

on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: build
        run: |
          yarn --frozen-lockfile
          yarn lint
          yarn tsc
          yarn run build
        env:
          CI: true
